//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xwheels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Admin
    {
        public int Admin_id { get; set; }
        public string Admin_name { get; set; }
        public string Admin_email { get; set; }
        public string Admin_password { get; set; }
        public string Admin_role { get; set; }
    }
}
