//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xwheels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Model()
        {
            this.tbl_Ads = new HashSet<tbl_Ads>();
        }
    
        public int Model_id { get; set; }
        public string Model_name { get; set; }
        public Nullable<int> Make_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ads> tbl_Ads { get; set; }
        public virtual tbl_Make tbl_Make { get; set; }
    }
}
